/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    kotlin("jvm") version "1.6.10"
}

group = "com.example"
version = "0.1.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Kotlin 표준 라이브러리
    implementation(kotlin("stdlib"))

    // 테스트를 위한 JUnit 의존성
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.0")
}

// Kotlin 컴파일러 옵션 설정
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "14" // 사용하는 JVM 버전에 맞춰 설정하세요
    }
}

// JUnit 5를 사용하기 위한 설정
tasks.test {
    useJUnitPlatform()
}

